[project]
name = "myapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.129.0",
    "pandas>=3.0.0",
    "rapidfuzz>=3.14.3",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.40.0",
]
